### ISSUE TITLE
Add .gitattributes file?

### ISSUE THREAD

**Issue by Crell** [Crell/ApiProblem#11]
Apparently it's a thing: 

http://blog.madewithlove.be/post/gitattributes/

**Comment by fbidu** [comment]
Yes... That post gave some clues about how we could it. Basically:
```
/tests export-ignore
/phpunit.xml.dist export-ignore
/.gitattributes export-ignore
/.gitignore export-ignore
/.travis.yml export-ignore
/README.md export-ignore
```

**Comment by Crell** [comment]
This was mostly a note-to-self. Can you file a PR?

**Comment by fbidu** [comment]
Yeah, sure!
