### ISSUE TITLE
Any reason why json_encode() is not supported?

### ISSUE THREAD

**Issue by judgej** [Crell/ApiProblem#26]
Syntactic sugar I know, but there are many instances where objects are put through `jason_encode()` to serialise them. Once example is Laravel or Lumen, where you can return an object and it will be encoded as a JSON payload, for example:

    return response()->json($problem);

It would be great if that were simply handled without converting to JSON first. The above example returns the payload as `[]` instead of an RFC7807 object.

These work for Laravel at present as the return from a controller:

    return response($problem->asJson(), $statusCode, ['Content-Type' => 'application/problem+json']);

    return response()->json($problem->asArray(), $statusCode);

I will look at the PSR-7 generation too, as that makes sense for other frameworks and simple apps.

Is this something that you prefer not to support, or just something nobody has got around to?

**Comment by Crell** [comment]
I am not entirely clear on what you're describing.  $problem->asJson() gives you a JSON string, which can then be put into any response body you want.  It uses json_encode() internally already.

**Comment by judgej** [comment]
`$problem->asJson()` returns a JSON string `{"title":"...etc"}`

`json_encode($problem)` returns an empty JSON string `{}`

It is handy in some frameworks to pass the object out of the controller for the framework to encode.

Like I say, it's just syntactic sugar, but mildly useful in some circumstances.

**Comment by Crell** [comment]
That's because ApiProblem has no public properties, so json_encode() has nothing to encode.

I think what you're asking for is to implement `JsonSerializable` on the object, which would return `$this->compile()`, which is an array, which json_encode() would then be able to work with.  

I'd accept a PR that does that.

**Comment by judgej** [comment]
Yes, exactly. I'll be happy to submit a PR. It's a busy week, but I'll aim to squeeze in. Thanks :-)
