### ISSUE TITLE
Make this project more reachable

### ISSUE THREAD

**Issue by szepeviktor** [Crell/ApiProblem#28]
> ![image](https://user-images.githubusercontent.com/952007/62742745-11c04f80-ba40-11e9-8789-2c8b19f3679e.png)

maybe add an URL too

**Comment by Crell** [comment]
Er... I don't know what you're describing?  Are you talking about adding a bunch of links to the README, or a Github thing, or...?

**Comment by szepeviktor** [comment]
at the top of this page: https://github.com/Crell/ApiProblem
the repo description and the topics

**Comment by Crell** [comment]
Oh!  I didn't even see the "manage topics" link there.  Yeah, makes sense, I'll throw in some tags.

**Comment by szepeviktor** [comment]
Thanks.

Now you can: https://github.com/topics/rfc-7807

**Comment by Crell** [comment]
Oh, look, this library's on top! :smile:

**Comment by szepeviktor** [comment]
This library has a 🌟 starry sky 🌟
