### ISSUE TITLE
fromJson method doesn't throw an appropriate exception for invalid JSON

### ISSUE THREAD

**Issue by becw** [Crell/ApiProblem#3]
When invalid JSON is passed to ```ApiProblem::fromJson()```, I get a PHP notice and an exception:
* Argument 1 passed to Crell\ApiProblem\ApiProblem::decompile() must be an array, null given
* The provided problem string is invalid. The "title" property is required.

I think it would be appropriate to throw an exception about the invalid JSON, rather than one about the missing title.

**Comment by Crell** [comment]
JSON has been resolved here: https://github.com/Crell/ApiProblem/pull/14
